name: scaffold_responsive
description: A responsive scaffold widget that adjusts to your device size, for your flutter mobile and web apps.
version: 1.1.2
repository: https://github.com/tusharsadhwani/scaffold_responsive

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter

flutter: